### ISSUE TITLE
DOMParser

### ISSUE THREAD

**Issue by FrankC01** [joshuamiller/cljs-tvos#1]
Josh, nice work and 1 nit:

For parsing you create a DOMParser instance every time you compile a document. Whereas it would be more performant and less memory to create a parser singleton (atom? JS variable?).

Again, this is a NIT so feel free to ignore.

**Comment by joshuamiller** [comment]
@FrankC01 I had had that debate internally with myself, but decided the overhead of creating and maintaining a singleton parser wasn't really worth it, since you likely wouldn't instantiate it over and over so quickly that the GC wouldn't handle it. If you're in that kind of situation, I imagine you'd want to just handle that manually.

**Comment by FrankC01** [comment]
No problem, thanks for responding!
